#!/bin/bash

# This file is included to run the file from here.
# This file is not required (this is optional).
# This file will only run on Linux platforms.
# The program must first be compiled to use this shell file.

./wulf
